### ISSUE TITLE
试了一下新版，发现无法修改公告。

### ISSUE THREAD

**Issue by falseen** [xuanhuan/ss-panel#12]
提示“错误200”，不知道什么原因。

**Comment by xuanhuan** [comment]
不知道你是否开了php内置的输出错误信息，如果开了，请关闭，
有可能是
lib/announcement.php 没有写权限，你用ftp看看，如果没有，要分配。

**Comment by falseen** [comment]
之前的版本是正常的。。。
其实我第一次装的时候就遇到了权限问题，当时没开PHP的错误提示，打开任何页面都是一片空白（从来没见过这种情况，任何一个页面都是空白啊），死活找不到原因（折腾了两天我都想放弃了）。后来开了错误提示才知道原来是没有写入的权限...所以建议在主页加个提示。

**Comment by falseen** [comment]
我看了一下  lib/announcement.php 是有写权限的。PHP的错误提示我还没关，关了的话太不方便了，出错都找不到原因。

![qq 20150821234232](https://cloud.githubusercontent.com/assets/11572353/9412451/5da3437e-485e-11e5-8797-f1c78d3a171e.jpg)

**Comment by xuanhuan** [comment]
在浏览器按F12打开开发者工具，然后点Network
再点修改，会在Network列表最后一个是刚才返回的文件_change_announcement.php 点一下，在右边窗口点Preview,下面就有所有信息了。

**Comment by falseen** [comment]
Warning: fopen(../lib/announcement.php): failed to open stream: Permission denied in /var/www/html/admin/_change_announcement.php on line 56

Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/admin/_change_announcement.php on line 78
{"code":"0","msg":"\u6587\u4ef6\u6253\u4e0d\u5f00"}

果然是权限问题，但是FTP上显示的权限是对的呀。。

**Comment by xuanhuan** [comment]
给读写权限

**Comment by falseen** [comment]
嗯 ，给了777权限之后好了。我还以为给跟之前的版本一样的权限就行了呢。

**Comment by xuanhuan** [comment]
其实是一样的

**Comment by falseen** [comment]
那就不知道了，反正看FTP上的权限跟之前是一样的。
这是现在的权限，必须给777，给775都不行。

![image](https://cloud.githubusercontent.com/assets/11572353/9415836/8ef26d54-4874-11e5-82c4-191d49c0cd5b.png)

**Comment by jason-akw** [comment]
你文件的持有者帳號和php的運行帳號是一樣的嗎
