### ISSUE TITLE
首页自定义内容在手机上显示不完全。

### ISSUE THREAD

**Issue by falseen** [xuanhuan/ss-panel#14]
应该不用上图了吧。。。。
另外下面三个点击展开的列表在手机上很卡-------在uc浏览器上列表展开的很慢，chrome浏览器没问题。但国内大部分都用的uc，所以我觉得这个列表可以考虑去掉（我的网站已经去掉了），毕竟用户体验很重要。

**Comment by xuanhuan** [comment]
这个只能用响应式控制，正在做。

**Comment by xuanhuan** [comment]
已修复 https://github.com/xuanhuan/ss-panel/commit/ba91278e1c645ccf1c3c40849c2ebdd648e8ea6e
