### ISSUE TITLE
update.php修改Shadowsocks连接密码问题

### ISSUE THREAD

**Issue by prajna0** [xuanhuan/ss-panel#18]
最近看到禁用功能，然后也进行了测试，确实可以，但是发现一个问题，在正常状态下，直接点击"修改"按钮会直接默认修改为其它密码

**Comment by falseen** [comment]
不会吧？我这边没问题。你说哪个密码？

**Comment by prajna0** [comment]
@falseen Shadowsocks连接密码，在正常状态，可以直接不输入要修改的密码可以点击修改按钮。

**Comment by falseen** [comment]
你说的是用户中心的还是后台的？

**Comment by prajna0** [comment]
@falseen 用户中心的

**Comment by falseen** [comment]
哦，看到了，不输入新密码的话会随机生成一个密码。这个功能还可以吧，反正可以随时查看自己的连接密码。

**Comment by ArnaudGithub** [comment]
@falseen @xuanhuan 嗯嗯，不过邮件找回功能，在修改密码的时候提示错误500 这如何解决？

**Comment by xuanhuan** [comment]
@ArnaudGithub 这是原来就有的功能，我之所以在被禁用时，也禁止修改连接密码，也是出于这方面考虑。

**Comment by prajna0** [comment]
@xuanhuan 恩，禁用这个确实很不错~
