### ISSUE TITLE
提个建议，最需要解决的问题

### ISSUE THREAD

**Issue by liuchao0130** [xuanhuan/ss-panel#22]
首先ss-panel 做的很不错，基本功能都有了，界面非常简洁直观。
用了一段时间，我觉得SS-panel 目前最需要解决的是3个问题，就非常完美了

1、 套餐的设定    我看到里面有保留字段 A  B  应该就是实现这个功能，是否考虑增加一个plan表，用来存套餐的配置？
2、 帐号有效期   既然有套餐就肯定有一个有效期，  只要在user表增加一个 过期时间 的字段， 目前我的实现方法就是这个，但是由于我PHP真的是不熟，对SS-Panel的架构更是不懂，我是通过数据库添加事件，每天晚上12点定期执行，对比 过期时间 来实现自动停用帐号， 希望大神们可以帮忙通过PHP来实现这个。
  （当然最新版有 停用功能，但是需要手动吧，得有一个明确的过期时间比较好）
3、 支付接口     带上接收返回值， 这个我不懂，但是很希望可以有。  

我认为这3个才是目前需要解决的问题，其他界面什么优化 什么细节 都没有这几个重要。。

**Comment by liuchao0130** [comment]
php大神们，出手吧， 一起解决这几个问题撒~~~

**Comment by falseen** [comment]
嗯，我也是这样觉得。可惜我也是不懂php…

**Comment by xuanhuan** [comment]
第一个我没想过，第二个问题我正在尝试想办法，目前我做的思路是通过签到，如果一周都没签到，就会自动停止，然后要签到1天才会恢复，但是第2,3天没连续签到，一样还会停止，就是说要连续签到3天，之后最少要一周签到一次。
目前想用SQLite来做，把这些次要数据放在SQLite，达到节省内存和高性能目的，但是遇到一个问题，SQLite在多线程模式下，可以同时多个线程读取，但是只能一个线程写入数据。
第三个问题我之前有想过，但是没做过，不知怎么去做，而且像现在支付宝的支付接口那几个，还要什么申请的，我没这些东西，也做不来。

**Comment by liuchao0130** [comment]
现在不流行签到了吧 我们是做翻墙呀， 这是一个管理系统嘛  主要是对账户的管理 。 
先把基础的重要的功能解决了再弄 别的 。
  比如， 账户有效期 ， 增加一个字段 有效期， 然后写一个 计划任务的PHP文件 ，即可解决。
  套餐， 这个也应该不难呀， 添加一个表，用来存配置数据，注册的时候就可以选择相应的配置
支付借口 可以以后再搞

**Comment by xuanhuan** [comment]
@liuchao0130 
其实这个项目我从来就没打算做支付系统，也就是说这个项目只适用的是给大家提供免费（也可以是赞助
、捐助）的站长，如果你认为要做支付系统，你可以自己做，也可以考虑购买别人做好的那个什么SS，顺带提醒一句话，在国内做收费翻墙服务的后果很严重。

**Comment by liuchao0130** [comment]
有点道理。那就不做支付系统
