### ISSUE TITLE
旧版如何使用新的加密方式

### ISSUE THREAD

**Issue by liuchao0130** [xuanhuan/ss-panel#23]
之前用的是MD5加密的 ， 我怎么样才可以用到新的加密呢？
说明 弄到64位？怎么弄呢？　可否指点下。。

**Comment by falseen** [comment]
改数据库似乎没用，我之前怎么改都登不上。只能用邮件重置管理密码，然后用管理帐号一个个修改。

**Comment by xuanhuan** [comment]
你仔细看说明

新版密码加密方式说明
当使用新的加密方式「带salt的sha256」加密，由于每个站点的$salt值都不同，

访问 /pwd.php?pwd=新密码
将获得的字符串更新到数据库user表的pass字段。

注意：

$salt 不可随意修改！
如果原来为2.4之前的版本，需要将pass字段的长度修改为64

**Comment by falseen** [comment]
@xuanhuan 原来是这样，我之前是用在线转换工具转换的，也加了盐值。
