### ISSUE TITLE
安装完打开页面一片空白，lamp设置均没问题，其他版本sspanel可以用，哪里的问题？

### ISSUE THREAD

**Issue by travelbob2005** [xuanhuan/ss-panel#35]
请教，安装完打开页面一片空白，lamp设置均没问题，其他版本sspanel可以用，这个版本安装完，页面空白，哪里的问题？

**Comment by xuanhuan** [comment]
看说明

**Comment by falseen** [comment]
权限问题。

**Comment by travelbob2005** [comment]
orvice/ss-panel这个版本可以用，权限没问题，root帐号都不行

**Comment by travelbob2005** [comment]
问题依然，请赐教，多谢！

**Comment by falseen** [comment]
可以参考这个 https://github.com/xuanhuan/ss-panel/issues/12

**Comment by falseen** [comment]
把web目录的所有者改为apache的默认账户www-data应该就没问题了（如果你用的是apache的话）。

**Comment by travelbob2005** [comment]
好了，果然是一个愚蠢的错误，源码没有上传完。。。

**Comment by PlaneV** [comment]
config.php的问题吧？

2015-09-10 16:24 GMT+08:00 xuanhuan notifications@github.com:
