### ISSUE TITLE
后台无法编辑公告

### ISSUE THREAD

**Issue by travelbob2005** [xuanhuan/ss-panel#37]
保存之后，这个提示
![20150911084014](https://cloud.githubusercontent.com/assets/12201477/9804538/756dc89a-5861-11e5-9836-7cdb1ab1d34b.png)

**Comment by falseen** [comment]
权限

**Comment by xuanhuan** [comment]
如果是在SSH用命令解压、上传的，要给777权限。
一般用网站管理/FTP解压的，通常不会有权限读写问题。

**Comment by liuchao0130** [comment]
是给网站根目录777权限吗？  还是给哪个

**Comment by liuchao0130** [comment]
我给了根目录权限 admin目录 ，最后把 根目录下面 所有的 chmod 777 \*  都不能改公告 为啥呢

**Comment by falseen** [comment]
chmod -R 777 根目录所有文件都给777试试

**Comment by liuchao0130** [comment]
搞定了 。。 只要lib 下的 那个 an文件就行了。   纠结

**Comment by falseen** [comment]
建议你把web目录的所有者改成网站的运行帐户，比如apache的是www:data，以后就不会有权限问题了。
