### ISSUE TITLE
test-mail-smtp.php無法使用

### ISSUE THREAD

**Issue by jason-akw** [xuanhuan/ss-panel#4]
錯誤信息
"
Warning: require_once(/XXXX/lib/MailSmtp.php): failed to open stream: No such file or directory in /XXXX/lib/do.php on line 39

Fatal error: require_once(): Failed opening required '/XXXX/lib/MailSmtp.php' (include_path='.:/usr/share/php:/usr/share/pear') in /XXXX/lib/do.php on line 39

**Comment by jason-akw** [comment]
另外smtp設定好之後，信件也沒發出去-_-||
是我少安裝甚麼嗎? php-pear也安裝了呀

**Comment by xuanhuan** [comment]
需要开启php扩展：sockets、Fileinfo和openssl。

**Comment by xuanhuan** [comment]
@akw28888 如果不发送附件，Fileinfo就不用开启。当然，只使用普通连接（0），那么只需要开启sockets就行了，但是不安全。

**Comment by xuanhuan** [comment]
问题已修复，https://github.com/xuanhuan/ss-panel/blob/smarty/lib/test-mail-smtp.php
