### ISSUE TITLE
求教： 如果实现用户登录后user/用旧版本模版 

### ISSUE THREAD

**Issue by liuchao0130** [xuanhuan/ss-panel#44]
1、 我喜欢新模版的主界面 ，和 admin /界面
2、 我不喜欢user/ 的用户中心的新模版界面 
有没有办法实现刚进网站是新模版， 而用户点登录之后，用户中心默认使用旧模版~~求实现方法

**Comment by xuanhuan** [comment]
请参考templates/materialize/asset/js/templates.js
