### ISSUE TITLE
纠结，为何模版user/下的 .tpl，里面插入单选框无法显示

### ISSUE THREAD

**Issue by liuchao0130** [xuanhuan/ss-panel#45]
为何模版user/下的 .tpl，里面插入单选框无法显示
<input name="time" type="radio" value="123" />
根本不显示呀， 有没有解决方法

**Comment by liuchao0130** [comment]
我在 dw中预览是没有问题的 ，传上去就不显示了~~

**Comment by falseen** [comment]
代码贴出来看看。

**Comment by liuchao0130** [comment]
咦，我记得我复制了呀， 怎么没有 。。截图好了‘
![2](https://cloud.githubusercontent.com/assets/13215589/9880048/8caa7348-5bfc-11e5-953e-da991ece2fb8.png)

**Comment by liuchao0130** [comment]
![1](https://cloud.githubusercontent.com/assets/13215589/9880000/67bab12e-5bfc-11e5-8a3e-bdc491decfc3.png)

**Comment by xuanhuan** [comment]
``` html
<form action="#">
    <p>
      <input name="group1" type="radio" id="test1" />
      <label for="test1">Red</label>
    </p>
    <p>
      <input name="group1" type="radio" id="test2" />
      <label for="test2">Yellow</label>
    </p>
    <p>
      <input class="with-gap" name="group1" type="radio" id="test3"  />
      <label for="test3">Green</label>
    </p>
      <p>
        <input name="group1" type="radio" id="test4" disabled="disabled" />
        <label for="test4">Brown</label>
    </p>
  </form>
```

请参考这个
更多请看http://materializecss.com/forms.html

**Comment by liuchao0130** [comment]
嗯  单选框好了， 接下来又有一个问题了，我要点击单选框的时候产生一个事件， 
<input class="with-gap" name="pingjia" type="radio" value="1" onClick="change(“速度”)">
这样， 后面的 onClick失效，造成单选框无法点击。。。有办法吗

**Comment by liuchao0130** [comment]
onClick失效 ，造成单选框无法选择
![4](https://cloud.githubusercontent.com/assets/13215589/9883210/5fa16ece-5c0b-11e5-90cf-ddf98632a64d.png)

**Comment by xuanhuan** [comment]
你看控制台报什么错

**Comment by liuchao0130** [comment]
我发现这个 ，input  radio单选框，不能用value参数哦。用了就会无法选择。这样的话，如何那不是不能赋值了~~
![5](https://cloud.githubusercontent.com/assets/13215589/9884709/cb1092b8-5c13-11e5-948c-da4f2be3e923.png)

**Comment by xuanhuan** [comment]
http://www.helloweba.com/view-blog-295.html
用其它的
