### ISSUE TITLE
用SMTP为何收不到重置密码邮件

### ISSUE THREAD

**Issue by liuchao0130** [xuanhuan/ss-panel#47]
stmp 方式，为何收不到邮件呢 
麻烦帮我看下去我的设置还有哪里要改吗？
![6](https://cloud.githubusercontent.com/assets/13215589/9931250/a5ddc664-5d6c-11e5-8a17-83941ce70da8.png)

**Comment by prajna0** [comment]
发件的时候显示已发送吗？检查一下帐号密码，然后再登陆邮箱看看是否有发件记录，另外需要php扩展sockets/fileinfo/openssl

**Comment by liuchao0130** [comment]
php扩展 已经全部安装， 发送的时候显示已发送，然后我登录gamil邮箱，提示阻止了不安全的设备登录，IP就是我的VPS  。。 
然后，我就到安全设置里面设置 允许不安全的设备登录  。
但是我再次发送的时候，它还是提示不未知设备，已阻止。。

有没有人试过用gmail.邮箱呢？ 是不是 gmail邮箱不支持。。
或者有其他邮箱推荐吗

**Comment by liuchao0130** [comment]
我发现 github 最近老是传不上图片。昨天传一个图片 传了N次。 
今天传了10来次了 还是没传上

**Comment by liuchao0130** [comment]
![2](https://cloud.githubusercontent.com/assets/13215589/9954686/8f8b2706-5e1d-11e5-8e9f-af27243e91aa.png)

**Comment by liuchao0130** [comment]
![3](https://cloud.githubusercontent.com/assets/13215589/9954728/e364abc2-5e1d-11e5-88c3-5f5b3a1def74.png)

**Comment by liuchao0130** [comment]
我现在又试了试，  提示已成功发送， gmail也没有提示阻止， 但是还是没收到邮件
我用gmail给自己的邮箱发了一个邮件 很快就收到了

**Comment by liuchao0130** [comment]
头大了 ，我换了163的邮箱也不行 。。 唉 。 求指点呀

**Comment by liuchao0130** [comment]
谢谢， 搞定了 。 用的 163邮箱，  密码需要用客户端授权码 ，而不是邮箱的密码。。要注意。
开启STMP的时候会发给你这个密码的。
