### ISSUE TITLE
求救，这下搞大了

### ISSUE THREAD

**Issue by liuchao0130** [xuanhuan/ss-panel#55]
1、 我把admin/login.php文件改了一下 ，然后后台就无法登录了提示： 500错误
2、我把代码改回之前一模一样，但是还是一样500错误，我重启机器，也还是一样，怎么办呢
这个系统，只要改了代码，再改就没用了吗？？ 还是啥原因，好郁闷啊 后台进不了了
3、无论输入什么用户名和密码都提示 500错误，就好像根本就没有验证帐号密码

这是 最初的代码
![qq 20150929002719](https://cloud.githubusercontent.com/assets/13215589/10141819/36d4a340-6641-11e5-80e0-bc192639fc89.png)

改为这样：
![qq 20150929002641](https://cloud.githubusercontent.com/assets/13215589/10141829/4361adb0-6641-11e5-88a4-cf18be00d09f.png)

500错误，无法登录，之后再如何修改回来， 或者把整个程序都删了，用之前的备份进去 也还是500错误

![qq 20150929002531](https://cloud.githubusercontent.com/assets/13215589/10141849/5c58edec-6641-11e5-824c-126ed6e0a2b0.png)

**Comment by liuchao0130** [comment]
手机记住了密码后台 还可以稍微用一下，只要是新设备，或者退出了帐号，都无法登录了
求帮看下什么问题，怎么解决

**Comment by xuanhuan** [comment]
你的mysql配置是正确的吗？

**Comment by xuanhuan** [comment]
删除编译文件
templates_c

**Comment by xuanhuan** [comment]
我用了这么久，从来没出现这个情况。

**Comment by liuchao0130** [comment]
好郁闷啊  ，删除templates_c目录里面的文件，还是不行。。是不是还有其他地方保存了设置

**Comment by liuchao0130** [comment]
mysql肯定配置正确， 一直在用的， 就是改了一下Login.php，就出错了，然后换回来也一样。。 
就跟我昨天改了 状态按钮一样，  换成了状态按钮的代码， 再换回文本的就无法换回来了，永远是按钮

**Comment by liuchao0130** [comment]
我去。 自己搞错了 ，多加了2个+号。。去掉就好了

**Comment by xuanhuan** [comment]
另外我提个建议，如果要用图片做背景，请找支持https大流量的图床网站，然后把网址粘在css相应位置，不要用自己的网站来加载图片。
