### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by mokitoo** [xuanhuan/ss-panel#7]
希望能有所改进，谢谢
1.管理员后台的用户管理的滚动条在chrome上显示太短了，要滑好久，有没有更好的方案，比如支持用户分组显示之类的？
2.管理员后台底部的tos路径错误，tos.php不存在，不过我觉得管理员看不看这个无所谓。。。
3.目前总之用起来体验不错，感谢作者

**Comment by xuanhuan** [comment]
你截图给我看看

**Comment by mokitoo** [comment]
![qq 20150816205055](https://cloud.githubusercontent.com/assets/4065940/9293308/942face8-4458-11e5-8fb3-4426221ba187.png)
滚动条太短了，看起来很费力的感觉。感觉分组可能更好一点

**Comment by xuanhuan** [comment]
https://github.com/xuanhuan/ss-panel/blob/smarty/templates/AdminLTE-2/admin/user.tpl
89行

``` js
"sScrollY": 395,
```

这个数值是表格高度，你可以任意调整，目前好像是不能自适应高度，为了小屏幕也能正常使用，所以数值是小了一点。

**Comment by mokitoo** [comment]
恩，改成1000看着舒服多了。

**Comment by liuchao0130** [comment]
请问楼主 你是怎么实现分页的

**Comment by xuanhuan** [comment]
DataTables

**Comment by xuanhuan** [comment]
@604542720 2.管理员后台底部的tos路径错误，tos.php不存在?
已修复。

**Comment by ArnaudGithub** [comment]
@xuanhuan https://github.com/xuanhuan/ss-panel/blob/smarty/templates/AdminLTE-2/admin/user.tpl

添加第54行页面出现白屏，请问是怎么回事！

**Comment by prajna0** [comment]
@xuanhuan 什么时候能修复下发件问题~

**Comment by xuanhuan** [comment]
@ArnaudGithub 是重置密码的吗？有什么问题吗？

**Comment by prajna0** [comment]
@xuanhuan 对，确实是重置密码的问题，不知道的程序的原因还是我的原因，无法正常发件。

**Comment by mokitoo** [comment]
@ArnaudGithub  可以发的，你检查下配置

**Comment by 604542720** [comment]
@ArnaudGithub  可以发的，你检查下配置

**Comment by 604542720** [comment]
@ArnaudGithub  可以发的，你检查下配置

**Comment by 604542720** [comment]
@ArnaudGithub  可以发的，你检查下配置

**Comment by xuanhuan** [comment]
请问你在配置里用的是那个发邮件服务？

**Comment by prajna0** [comment]
@604542720 好的，我检查一下。

**Comment by prajna0** [comment]
@xuanhuan 我使用的是STMP。

**Comment by xuanhuan** [comment]
需要的php配置扩展：sockets、Fileinfo和openssl，你看看是否都开启了。

**Comment by prajna0** [comment]
@xuanhuan 好，我等下检查一下，遇到一个问题，站点刚被GFW列入列表。

**Comment by xuanhuan** [comment]
....换IP吧，不行就换机房。。。

**Comment by prajna0** [comment]
@xuanhuan 恩，正在采购新域名和备份网站文件
