### ISSUE TITLE
SS-PANEL已更新

### ISSUE THREAD

**Issue by prajna0** [xuanhuan/ss-panel#8]
感谢作者开源提供精神~

也不是催作者，只是让提醒下作者~

**Comment by PlaneV** [comment]
你真不应该催更，其实作者也非常不容易，平时一大堆事情等着处理，业余时间能搞出这个项目来已经很让人佩服了！我自己想搞出点什么东西来也经常抽不出时间，所以我是很能理解的。
从作者的行事来看，是一个很负责的人，但凡能抽出点时间，还能忘了这件事？所以大家不应该催，说白了，人家这是义务劳动，纯粹兴趣！

2015-08-17 11:47 GMT+08:00 Arnaud notifications@github.com:

**Comment by mokitoo** [comment]
同意楼上

**Comment by prajna0** [comment]
@PlaneV @604542720 这个我知道所以我在后面写了不是催作者，只是小小提醒一下。

**Comment by PlaneV** [comment]
你的心情大家也能理解，稍安勿躁，稍微有点耐心，等等就好。如果有闲暇时间，帮忙一起改进一下不也挺好？哪怕添加一个小图标，增加一个判断条件，修补一个小bug也是贡献嘛。

2015-08-17 12:03 GMT+08:00 Arnaud notifications@github.com:

**Comment by prajna0** [comment]
@PlaneV 嗯，这个建议不错~ 慢慢等

**Comment by xuanhuan** [comment]
2.4.5不考虑更新，功能没有变化。（相对当前smarty分支而言，基本上是在跟进更新的）
